/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IRewardsCoordinator {
  export type StrategyAndMultiplierStruct = {
    strategy: AddressLike;
    multiplier: BigNumberish;
  };

  export type StrategyAndMultiplierStructOutput = [
    strategy: string,
    multiplier: bigint
  ] & { strategy: string; multiplier: bigint };

  export type RewardsSubmissionStruct = {
    strategiesAndMultipliers: IRewardsCoordinator.StrategyAndMultiplierStruct[];
    token: AddressLike;
    amount: BigNumberish;
    startTimestamp: BigNumberish;
    duration: BigNumberish;
  };

  export type RewardsSubmissionStructOutput = [
    strategiesAndMultipliers: IRewardsCoordinator.StrategyAndMultiplierStructOutput[],
    token: string,
    amount: bigint,
    startTimestamp: bigint,
    duration: bigint
  ] & {
    strategiesAndMultipliers: IRewardsCoordinator.StrategyAndMultiplierStructOutput[];
    token: string;
    amount: bigint;
    startTimestamp: bigint;
    duration: bigint;
  };
}

export declare namespace IHelloWorldServiceManager {
  export type TaskStruct = { name: string; taskCreatedBlock: BigNumberish };

  export type TaskStructOutput = [name: string, taskCreatedBlock: bigint] & {
    name: string;
    taskCreatedBlock: bigint;
  };
}

export declare namespace ISignatureUtils {
  export type SignatureWithSaltAndExpiryStruct = {
    signature: BytesLike;
    salt: BytesLike;
    expiry: BigNumberish;
  };

  export type SignatureWithSaltAndExpiryStructOutput = [
    signature: string,
    salt: string,
    expiry: bigint
  ] & { signature: string; salt: string; expiry: bigint };
}

export interface HelloWorldServiceManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allTaskHashes"
      | "allTaskResponses"
      | "avsDirectory"
      | "createAVSRewardsSubmission"
      | "createNewTask"
      | "deregisterOperatorFromAVS"
      | "getOperatorRestakedStrategies"
      | "getRestakeableStrategies"
      | "latestTaskNum"
      | "owner"
      | "registerOperatorToAVS"
      | "renounceOwnership"
      | "respondToTask"
      | "rewardsInitiator"
      | "setRewardsInitiator"
      | "stakeRegistry"
      | "transferOwnership"
      | "updateAVSMetadataURI"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "NewTaskCreated"
      | "OwnershipTransferred"
      | "RewardsInitiatorUpdated"
      | "TaskResponded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allTaskHashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allTaskResponses",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "avsDirectory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createAVSRewardsSubmission",
    values: [IRewardsCoordinator.RewardsSubmissionStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createNewTask",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deregisterOperatorFromAVS",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOperatorRestakedStrategies",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRestakeableStrategies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "latestTaskNum",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerOperatorToAVS",
    values: [AddressLike, ISignatureUtils.SignatureWithSaltAndExpiryStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "respondToTask",
    values: [IHelloWorldServiceManager.TaskStruct, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardsInitiator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardsInitiator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAVSMetadataURI",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "allTaskHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allTaskResponses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "avsDirectory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAVSRewardsSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createNewTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deregisterOperatorFromAVS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOperatorRestakedStrategies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRestakeableStrategies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestTaskNum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerOperatorToAVS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "respondToTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardsInitiator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardsInitiator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAVSMetadataURI",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewTaskCreatedEvent {
  export type InputTuple = [
    taskIndex: BigNumberish,
    task: IHelloWorldServiceManager.TaskStruct
  ];
  export type OutputTuple = [
    taskIndex: bigint,
    task: IHelloWorldServiceManager.TaskStructOutput
  ];
  export interface OutputObject {
    taskIndex: bigint;
    task: IHelloWorldServiceManager.TaskStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsInitiatorUpdatedEvent {
  export type InputTuple = [
    prevRewardsInitiator: AddressLike,
    newRewardsInitiator: AddressLike
  ];
  export type OutputTuple = [
    prevRewardsInitiator: string,
    newRewardsInitiator: string
  ];
  export interface OutputObject {
    prevRewardsInitiator: string;
    newRewardsInitiator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskRespondedEvent {
  export type InputTuple = [
    taskIndex: BigNumberish,
    task: IHelloWorldServiceManager.TaskStruct,
    operator: AddressLike
  ];
  export type OutputTuple = [
    taskIndex: bigint,
    task: IHelloWorldServiceManager.TaskStructOutput,
    operator: string
  ];
  export interface OutputObject {
    taskIndex: bigint;
    task: IHelloWorldServiceManager.TaskStructOutput;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HelloWorldServiceManager extends BaseContract {
  connect(runner?: ContractRunner | null): HelloWorldServiceManager;
  waitForDeployment(): Promise<this>;

  interface: HelloWorldServiceManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allTaskHashes: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  allTaskResponses: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  avsDirectory: TypedContractMethod<[], [string], "view">;

  createAVSRewardsSubmission: TypedContractMethod<
    [rewardsSubmissions: IRewardsCoordinator.RewardsSubmissionStruct[]],
    [void],
    "nonpayable"
  >;

  createNewTask: TypedContractMethod<
    [name: string],
    [IHelloWorldServiceManager.TaskStructOutput],
    "nonpayable"
  >;

  deregisterOperatorFromAVS: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  getOperatorRestakedStrategies: TypedContractMethod<
    [_operator: AddressLike],
    [string[]],
    "view"
  >;

  getRestakeableStrategies: TypedContractMethod<[], [string[]], "view">;

  latestTaskNum: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerOperatorToAVS: TypedContractMethod<
    [
      operator: AddressLike,
      operatorSignature: ISignatureUtils.SignatureWithSaltAndExpiryStruct
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  respondToTask: TypedContractMethod<
    [
      task: IHelloWorldServiceManager.TaskStruct,
      referenceTaskIndex: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  rewardsInitiator: TypedContractMethod<[], [string], "view">;

  setRewardsInitiator: TypedContractMethod<
    [newRewardsInitiator: AddressLike],
    [void],
    "nonpayable"
  >;

  stakeRegistry: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAVSMetadataURI: TypedContractMethod<
    [_metadataURI: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allTaskHashes"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "allTaskResponses"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "avsDirectory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createAVSRewardsSubmission"
  ): TypedContractMethod<
    [rewardsSubmissions: IRewardsCoordinator.RewardsSubmissionStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createNewTask"
  ): TypedContractMethod<
    [name: string],
    [IHelloWorldServiceManager.TaskStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deregisterOperatorFromAVS"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getOperatorRestakedStrategies"
  ): TypedContractMethod<[_operator: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRestakeableStrategies"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "latestTaskNum"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerOperatorToAVS"
  ): TypedContractMethod<
    [
      operator: AddressLike,
      operatorSignature: ISignatureUtils.SignatureWithSaltAndExpiryStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "respondToTask"
  ): TypedContractMethod<
    [
      task: IHelloWorldServiceManager.TaskStruct,
      referenceTaskIndex: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewardsInitiator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setRewardsInitiator"
  ): TypedContractMethod<
    [newRewardsInitiator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAVSMetadataURI"
  ): TypedContractMethod<[_metadataURI: string], [void], "nonpayable">;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "NewTaskCreated"
  ): TypedContractEvent<
    NewTaskCreatedEvent.InputTuple,
    NewTaskCreatedEvent.OutputTuple,
    NewTaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardsInitiatorUpdated"
  ): TypedContractEvent<
    RewardsInitiatorUpdatedEvent.InputTuple,
    RewardsInitiatorUpdatedEvent.OutputTuple,
    RewardsInitiatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskResponded"
  ): TypedContractEvent<
    TaskRespondedEvent.InputTuple,
    TaskRespondedEvent.OutputTuple,
    TaskRespondedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "NewTaskCreated(uint32,tuple)": TypedContractEvent<
      NewTaskCreatedEvent.InputTuple,
      NewTaskCreatedEvent.OutputTuple,
      NewTaskCreatedEvent.OutputObject
    >;
    NewTaskCreated: TypedContractEvent<
      NewTaskCreatedEvent.InputTuple,
      NewTaskCreatedEvent.OutputTuple,
      NewTaskCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardsInitiatorUpdated(address,address)": TypedContractEvent<
      RewardsInitiatorUpdatedEvent.InputTuple,
      RewardsInitiatorUpdatedEvent.OutputTuple,
      RewardsInitiatorUpdatedEvent.OutputObject
    >;
    RewardsInitiatorUpdated: TypedContractEvent<
      RewardsInitiatorUpdatedEvent.InputTuple,
      RewardsInitiatorUpdatedEvent.OutputTuple,
      RewardsInitiatorUpdatedEvent.OutputObject
    >;

    "TaskResponded(uint32,tuple,address)": TypedContractEvent<
      TaskRespondedEvent.InputTuple,
      TaskRespondedEvent.OutputTuple,
      TaskRespondedEvent.OutputObject
    >;
    TaskResponded: TypedContractEvent<
      TaskRespondedEvent.InputTuple,
      TaskRespondedEvent.OutputTuple,
      TaskRespondedEvent.OutputObject
    >;
  };
}
